languageExtensions = {
        'erl': 'erlang',
        'lua': 'lua',
        'el': 'elisp',
        'Makefile': 'make',
        'Dockerfile': 'dockerfile',
        'go.mod': 'go mod',
        'ex': 'elixir',
        'elm': 'elm',
        'kt': 'kotlin',
        'pl': 'perl',
        'md': 'markdown',
        'yaml': 'yaml',
        'm': 'objective-c',
        'sql': 'sql',
        'r': 'r',
        'dot': 'dot',
        'hack': 'hack',
        'lisp': 'common lisp',
        'sh': 'bash',
        'c': 'c',
        'cs': 'c#',
        'cpp': 'c++',
        'css': 'css',
        'et': 'embedded template',
        'go': 'go',
        'hs': 'haskell',
        'html': 'html',
        'java': 'java',
        'js': 'javascript',
        'json': 'json',
        'jl': 'julia',
        'ml': 'ocaml',
        'php': 'php',
        'py': 'python',
        'ql': 'ql',
        'regex': 'regex',
        'rb': 'ruby',
        'rs': 'rust',
        'scala': 'scala',
        'sqlite': 'sqlite',
        'toml': 'toml',
        'tsq': 'tsq',
        'ts': 'typescript',
        'rst': 'restructuredtext (rst)',
        'hcl': 'hcl',
        'f90': 'fortran',
        'f': 'fixed-form fortran',
        'tsx': 'typescript react',
        'jsx': 'javascript react'
}